const tutorsData = [
    { id: 1, name: "Dr. Abdur Rahman", email: "rahman@tutor.com", phone: "01711111111", subject: "Math", baseRate: 3500, perDayRate: 600, location: "Dhanmondi", qualification: "PhD in Mathematics, DU", experience: 12, bio: "Award-winning mathematician with 12+ years of teaching excellence.", avatar: "👨‍🏫", rating: 4.9, totalRatings: 128, reviews: [{ user: "Rahim", rating: 5, comment: "Exceptional teacher!", date: "2026-02-15" }] },
    { id: 2, name: "Prof. Fatema Begum", email: "fatema@tutor.com", phone: "01822222222", subject: "English", baseRate: 4000, perDayRate: 700, location: "Gulshan", qualification: "PhD in English, Oxford", experience: 15, bio: "Oxford-educated professor specializing in IELTS.", avatar: "👩‍🏫", rating: 4.95, totalRatings: 245, reviews: [] },
    { id: 3, name: "Dr. Hasan Mahmud", email: "hasan@tutor.com", phone: "01933333333", subject: "Physics", baseRate: 3800, perDayRate: 650, location: "Uttara", qualification: "M.Sc in Physics, BUET", experience: 10, bio: "Physics expert making complex concepts simple.", avatar: "👨‍🔬", rating: 4.7, totalRatings: 89, reviews: [] },
    { id: 4, name: "Prof. Kamal Hossain", email: "kamal@tutor.com", phone: "01644444444", subject: "Chemistry", baseRate: 3600, perDayRate: 600, location: "Mohammadpur", qualification: "M.Sc in Chemistry, DU", experience: 8, bio: "Chemistry specialist with passion for teaching.", avatar: "🧪", rating: 4.6, totalRatings: 67, reviews: [] },
    { id: 5, name: "Ms. Jahanara Akter", email: "jahanara@tutor.com", phone: "01555555555", subject: "Programming", baseRate: 5000, perDayRate: 800, location: "Banani", qualification: "B.Sc in CSE, BUET", experience: 6, bio: "Senior Software Engineer at Google.", avatar: "💻", rating: 4.98, totalRatings: 156, reviews: [] },
    { id: 6, name: "Dr. Sumaiya Islam", email: "sumaiya@tutor.com", phone: "01766666666", subject: "Biology", baseRate: 3400, perDayRate: 550, location: "Dhanmondi", qualification: "PhD in Molecular Biology", experience: 9, bio: "Biology expert for medical admission.", avatar: "👩‍🔬", rating: 4.8, totalRatings: 92, reviews: [] },
    { id: 7, name: "Mr. Tanvir Rahman", email: "tanvir@tutor.com", phone: "01877777777", subject: "Economics", baseRate: 3200, perDayRate: 500, location: "Mirpur", qualification: "M.Sc in Economics, JU", experience: 7, bio: "Economics expert for HSC and university.", avatar: "📊", rating: 4.5, totalRatings: 45, reviews: [] },
    { id: 8, name: "Ms. Sabrina Chowdhury", email: "sabrina@tutor.com", phone: "01988888888", subject: "Accounting", baseRate: 3500, perDayRate: 600, location: "Gulshan", qualification: "MBA in Accounting, IBA", experience: 11, bio: "Chartered Accountant teaching practical accounting.", avatar: "💰", rating: 4.85, totalRatings: 78, reviews: [] },
    { id: 9, name: "Dr. Rafiqul Islam", email: "rafiqul@tutor.com", phone: "01799999999", subject: "Physics", baseRate: 4200, perDayRate: 750, location: "Dhanmondi", qualification: "PhD in Physics, BUET", experience: 14, bio: "Advanced physics for competitive exams.", avatar: "👨‍🔬", rating: 4.92, totalRatings: 112, reviews: [] },
    { id: 10, name: "Ms. Nusrat Jahan", email: "nusrat@tutor.com", phone: "01811111111", subject: "Math", baseRate: 3600, perDayRate: 600, location: "Uttara", qualification: "M.Sc in Mathematics, DU", experience: 8, bio: "Mathematics expert for O and A Levels.", avatar: "👩‍🏫", rating: 4.75, totalRatings: 56, reviews: [] }
];

if (!localStorage.getItem('tutors')) {
    localStorage.setItem('tutors', JSON.stringify(tutorsData));
}